### ISSUE TITLE
Does anybody have example-code that demonstrates the use of TimerTwo?

### ISSUE THREAD

**Issue by StefanL38** [theAndreas/TimerTwo#1]
Hi everybody,

uploading a library without documentation forces each user to analyse the code completely.

That's not how I understand what libraries are for. 
libraries encapsulate functionality. If somebody is really interested he can analyse the *.h and *.cpp-file to know what is going on "under the hood"  For standard use there should be some documentation. 

best regards Stefan

**Comment by theAndreas** [comment]
Hi Stefan,

yes you are right. A documentation is very helpful but needs also a lot of time to create and maintain. This is my private repository. I use it to manage private projects. My code can be viewed and used by anyone, but you can't expect good documentation or maintenance. Added a small documentation and example for you. But be careful, not all functions of the library are tested.

Br Andreas
